services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: retail_api
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql://retail_user:retail_pass@db:5432/retail_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: retail_db
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: www.www
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retail_user -d retail_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
